###

POST http://localhost:3000/api/autores/crear
content-type: application/json

{
"nombre_completo": "Robert C. Martin",
"perfil": "https://cleancoders.com/images/portraits/robert-martin.jpg",
"info": "Esta es su información"
}

###

GET http://localhost:3000/api/libros/id/681ba93feb8034ebf54b78bf
content-type: application/json

###

PUT http://localhost:3000/api/autores/681b7488502682e5c050db50
content-type: application/json

{
"nombre_completo": "James Clear",
"perfil": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.planetadelibros.com.ar%2Fautor%2Fjames-clear%2F000050499&psig=AOvVaw2lmyQecJ-sbR-LhEF-1p0d&ust=1746716235830000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKCCyJfPkY0DFQAAAAAdAAAAABAE",
"info": "Esta es su información"
}

###

DELETE http://localhost:3000/api/autores/681b63b135175e6c49e79280
content-type: application/json

###

GET http://localhost:3000/api/libros/categoria/681cc1ec07d5b76b4c8ecbac
content-type: application/json

// LIBROS

###
POST http://localhost:3000/api/libros/crear
content-type: application/json

{
  "isbn": "9780132350884",
  "titulo": "Clean Code: A Handbook of Agile Software Craftsmanship",
  "idioma": "Inglés",
  "descripcion": "Un manual esencial sobre cómo escribir código limpio, legible y mantenible por Robert C. Martin, fundador del movimiento ágil.",
  "precio": 18000,
  "fecha_edicion": "2008-08-01T00:00:00Z",
  "portada": "https://m.media-amazon.com/images/I/51Dh8uVJxqL._SY291_BO1 ,204,203,200_QL40_FMwebp_.jpg",
  "formatos": ["fisico", "digital"],
  "autores": ["681cc13607d5b76b4c8ecba4"],
  "categorias": ["681cc1da07d5b76b4c8ecba9", "681cc1ec07d5b76b4c8ecbac"],
  "editorial": "681cc1b007d5b76b4c8ecba6"
}

###
POST http://localhost:3000/api/categorias/crear
content-type: application/json

{
    "nombre": "Negocios y finanzas"
}

###
POST http://localhost:3000/api/editoriales/crear
content-type: application/json

{
    "descripcion": "Pearson",
    "direccion": "",
    "imagen": "https://play-lh.googleusercontent.com/j96ohFvKdj7167zp100l1AoN7n4UoaQt2hJra5w76KdAXhc5tJrG1IVABP16xmtUKOov"
}